Create a class called Thermometer that has two pieces of information: a name (like “Kitchen Thermometer”) and a temperature reading (like 25.67). Add a method called read() that rounds the temperature to one decimal place and returns a sentence like “Kitchen Thermometer: 25.7°C”. Then, make two thermometers — one for the kitchen with temperature 25.67 and one for the bathroom with temperature 22.13. Put both of them into a list. Use a for loop to go through each thermometer and print the result of calling its read() method. Your output should show two lines, each with the name and rounded temperature followed by “°C”.

In [1]:
class Thermometer:
    def __init__(self, name, temperature):
        self.name = name
        self.temperature = temperature

    def read(self):
        rounded = round(self.temperature, 1)
        return f"{self.name}: {rounded}C"


kitchen = Thermometer("Kitchen Thermometer", 25.67)
bathroom = Thermometer("Bathroom Thermometer", 22.13)

thermometers = [kitchen, bathroom]

for t in thermometers:
    print(t.read())


Kitchen Thermometer: 25.7°C
Bathroom Thermometer: 22.1°C


Create a class called Book that stores three things: the title of the book (like “The Cat in the Hat”), the author’s name (like “Dr. Seuss”), and an ISBN number (like “001-234”). Then create another class called Bookshelf that starts with an empty list to hold books. Add a method called add_book(book) that lets you add a Book object to the list. Also add a method called list_titles() that goes through all the books and returns a list of just their titles. Now make three books: one titled “The Cat in the Hat” by Dr. Seuss with ISBN “001”, one titled “Green Eggs and Ham” by Dr. Seuss with ISBN “002”, and one titled “Harry Potter” by J.K. Rowling with ISBN “003”. Add all three books to a new Bookshelf. Finally, call the list_titles() method and print the result. You should see a list of the three book titles in square brackets.

In [2]:
class Book:
    def __init__(self, title, author, isbn):
        self.title = title
        self.author = author
        self.isbn = isbn


class Bookshelf:
    def __init__(self):
        self.books = []

    def add_book(self, book):
        self.books.append(book)

    def list_titles(self):
        return [book.title for book in self.books]


# Create books
b1 = Book("The Cat in the Hat", "Dr. Seuss", "001")
b2 = Book("Green Eggs and Ham", "Dr. Seuss", "002")
b3 = Book("Harry Potter", "J.K. Rowling", "003")

shelf = Bookshelf()
shelf.add_book(b1)
shelf.add_book(b2)
shelf.add_book(b3)

print(shelf.list_titles())


['The Cat in the Hat', 'Green Eggs and Ham', 'Harry Potter']


Use NumPy to make a grid of numbers. First, import NumPy using import numpy as np. Then create a 2-row by 3-column grid filled with random whole numbers from 1 to 5 using np.random.randint(1, 6, size=(2, 3)). Store this in a variable called box. Next, make a list called multipliers with two numbers: 2 and 3. Now make a copy of the grid and call it new_box. Multiply the first row of new_box by 2 (the first number in multipliers), and multiply the second row by 3 (the second number in multipliers). Finally, print the original box, the multipliers list, and the new new_box. Your output should show three parts: the original numbers, the two multipliers, and the new numbers after multiplying each row.

In [4]:
import numpy as np

box = np.random.randint(1, 6, size=(2, 3))

multipliers = [2, 3]

new_box = box.copy()
new_box[0] *= multipliers[0]   
new_box[1] *= multipliers[1]  
print("Original box:\n", box)
print("Multipliers:", multipliers)
print("New box:\n", new_box)


Original box:
 [[3 4 4]
 [5 2 1]]
Multipliers: [2, 3]
New box:
 [[ 6  8  8]
 [15  6  3]]
